<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- === Constants === -->
  <!--NOTE: This file should only contain constant values-->
<xacro:property name="base_height" value="0.3"/>
<xacro:property name="base_width" value="0.5"/>
<xacro:property name="base_length" value="0.65"/>

<xacro:property name="wheel_base" value="0.10"/>
<xacro:property name="wheel_radio" value="${base_height/2}"/> 
<xacro:property name="wheel_mass" value="3"/> 

<!-- TODO: Correct the caster_rad value -->
<xacro:property name="caster_rad" value="${wheel_radio}"/>

<xacro:property name="trans_ratio" value="1"/>
<!--Note: The direction should be signaled with as (1 || -1) -->


</robot>