<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_agv">
  <!-- Include constants xacro -->
  <xacro:include filename="$(find drivetrain)/urdf/constants.xacro" />
  
  <!-- === PARTS ONLY === -->

  <!-- = Wheels = -->
  <xacro:macro name="wheel_block" params="side invert parent_link">
    
    <!-- Link (physical part)-->
    <link name="wheel_${side}">  
      <visual>
        <!-- Shape -->
        <geometry>
          <cylinder length="${wheel_base}" radius="${wheel_radio}"/>
        </geometry>
        <!-- Origin relative to the link's joint -->
        <origin xyz= "0 0 0" rpy="${pi/2} 0 0"/>
        
        <material name="black">
          <color rgba="0 0 0 0.5"/>
        </material>
      </visual>
    </link>

    <!-- Joint (connection between links) -->
    <joint name="joint_wheel_${side}" type="continuous">
      <parent link="${parent_link}"/>
      <child link="wheel_${side}"/>

      <origin xyz="0 ${(base_length/2)*invert} ${wheel_radio}"/>
      <!-- Axis rotation-->
      <axis xyz="0 1 0"/> <!-- rpy="0 0 0 -->
      <!-- Joint limits (Newtons) (rad/s)-->
      <limit effort="50" velocity="20"/>
    </joint>
  
    <!-- Transmission -->
    <transmission name="trans_${side}">
      <!-- Type -->
      <type>transmission_interface/SimpleTransmission</type>
      <!-- Joint -->
      <joint name="joint_wheel_${side}">
        <hardwareInterface> hardware_interface/EffortJointInterface </hardwareInterface>
      </joint>
      <!-- Actuator -->
      <actuator name="motor_${side}">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  </xacro:macro>

  <!-- = Transmission = -->
  <!--Note: I use "*" as a separator -->
  <!-- <xacro:macro name="transmission_block" params="joint_name *side *direction">
    
  </xacro:macro> -->

  <!-- = Caster wheel = -->
  <xacro:macro name="caster_wheel_block" params="dir_x *dir_y ">
  <collision>
    <origin xyz="{$base_length/2*dir_x} ${$base_length/2*dir_y} ${caster_rad}" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${caster_rad}"/>
    </geometry>
    <surface>
      <friction>
        <ode>
          <slip1>0.0</slip1>
          <slip2>0.0</slip2>
        </ode>
      </friction>
    </surface>
  </collision>

  <visual>
    <origin xyz="{$base_length/2*dir_x} ${$base_length/2*dir_y} ${caster_rad}" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${caster_rad}"/>
    </geometry>
  </visual>

 </xacro:macro>

</robot> 